name: Build and Push to GHCR

on:
  push:
    branches: ["main"]

jobs:
  push-ghcr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # CHANGE: Bỏ setup Node.js vì Dockerfile tự build FE ở stage frontend-builder
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'

      # CHANGE: Không tạo .env từ secret DATABASE_URL trong image (truyền khi RUN)
      # - name: Tạo file .env từ secret DATABASE_URL
      #   run: |
      #     cat <<EOF > .env
      #     ${{ secrets.DATABASE_URL }}
      #     EOF

      # (tuỳ chọn) Giải mã cert nếu Dockerfile của bạn có COPY file này
      - name: Giải mã yugabyte.crt từ secret (optional)
        if: ${{ secrets.YUGA_CRT_B64 != '' }}
        run: |
          echo "${{ secrets.YUGA_CRT_B64 }}" | base64 -d > yugabyte.crt || true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/axum:latest
          docker build \
            --build-arg SQLX_OFFLINE=true \
            --build-arg VITE_BACKEND_URL="${{ secrets.VITE_BACKEND_URL }}" \
            -t $IMAGE_NAME .
          docker push $IMAGE_NAME
