name: Build and Push to GHCR vxcvxcvxcv

on:
  push:
    branches: ["main"]

jobs:
  push-ghcr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/axum
          TAG_LATEST=latest
          TAG_SHA=${{ github.sha }}

          echo "🛠️ Build image: $IMAGE:$TAG_LATEST và $IMAGE:$TAG_SHA"
          docker build -t $IMAGE:$TAG_LATEST -t $IMAGE:$TAG_SHA .

          echo "🚀 Push image với tag: $TAG_LATEST"
          docker push $IMAGE:$TAG_LATEST

          echo "📝 Push image với tag: $TAG_SHA"
          docker push $IMAGE:$TAG_SHA
